server:
  port: 8989

spring:
  application:
    name: gateway8989
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user-route
          uri: http://localhost:9999/
          predicates:
            - Path=/feign/**
#            - After=2020-08-20T15:50:49.001+08:00[Asia/Shanghai]
#            - Before=2020-08-20T14:50:49.001+08:00[Asia/Shanghai]
#            - Between=2020-08-20T14:50:49.001+08:00[Asia/Shanghai],2020-08-20T15:50:49.001+08:00[Asia/Shanghai]
#            - Cookie=username,lyz
#            - Cookie=username,[a-z]+
#            - Header=username,[a-z]+
#            - Method=POST,GET
#           filters:
#             - AddRequestParameter=name, R720
#             - AddResponseHeader=name, lyz
        - id: product-route
          uri: lb://products
          predicates:
            - Path=/products/**

      discovery:
        locator:
          enabled: true

management:
    endpoints:
      web:
        exposure:
          include: "*"
spring:
  rabbitmq:
    addresses: 192.168.121.129
    port: 5672
    username: lyz
    password: zxc970512





